-- MySQL Script generated by MySQL Workbench
-- seg 01 fev 2021 15:58:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gcom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gcom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gcom` ;
USE `gcom` ;

-- -----------------------------------------------------
-- Table `gcom`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gcom`.`categoria` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gcom`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gcom`.`fornecedor` (
  `frn_id` INT NOT NULL AUTO_INCREMENT,
  `frn_nome` VARCHAR(50) NOT NULL,
  `frn_doc` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`frn_id`),
  UNIQUE INDEX `frn_doc_UNIQUE` (`frn_doc` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gcom`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gcom`.`produto` (
  `pro_id` INT NOT NULL AUTO_INCREMENT,
  `pro_codigo` VARCHAR(100) NOT NULL,
  `pro_nome` VARCHAR(45) NOT NULL,
  `pro_valor_venda` DECIMAL(22,2) NOT NULL DEFAULT 0.00,
  `cat_id` INT NOT NULL,
  `frn_id` INT NOT NULL,
  PRIMARY KEY (`pro_id`),
  UNIQUE INDEX `pro_codigo_UNIQUE` (`pro_codigo` ASC) VISIBLE,
  INDEX `fk_produto_categoria_idx` (`cat_id` ASC) VISIBLE,
  INDEX `fk_produto_fornecedor1_idx` (`frn_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_categoria`
    FOREIGN KEY (`cat_id`)
    REFERENCES `gcom`.`categoria` (`cat_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_produto_fornecedor1`
    FOREIGN KEY (`frn_id`)
    REFERENCES `gcom`.`fornecedor` (`frn_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gcom`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gcom`.`estoque` (
  `est_id` INT NOT NULL AUTO_INCREMENT,
  `est_qtd_atual` INT NOT NULL DEFAULT 0,
  `est_qtd_minimo` INT NOT NULL DEFAULT 0,
  `pro_id` INT NOT NULL,
  PRIMARY KEY (`est_id`),
  INDEX `fk_estoque_produto1_idx` (`pro_id` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_produto1`
    FOREIGN KEY (`pro_id`)
    REFERENCES `gcom`.`produto` (`pro_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gcom`.`entrada_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gcom`.`entrada_produto` (
  `epr_id` INT NOT NULL AUTO_INCREMENT,
  `epr_data_cadastro` DATETIME NOT NULL,
  `epr_nfs_numero` VARCHAR(50) NULL,
  `epr_vlr_nota` DECIMAL(22,2) NOT NULL DEFAULT 0.00,
  `epr_vlr_prod_total` DECIMAL(22,2) NULL DEFAULT 0.00,
  `frn_id` INT NOT NULL,
  PRIMARY KEY (`epr_id`),
  INDEX `fk_entrada_produto_fornecedor1_idx` (`frn_id` ASC) VISIBLE,
  CONSTRAINT `fk_entrada_produto_fornecedor1`
    FOREIGN KEY (`frn_id`)
    REFERENCES `gcom`.`fornecedor` (`frn_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gcom`.`entrada_produto_detalhe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gcom`.`entrada_produto_detalhe` (
  `enp_id` INT NOT NULL AUTO_INCREMENT,
  `enp_qtd_entrada` INT NOT NULL DEFAULT 0,
  `enp_vlr_compra` DECIMAL(22,2) NOT NULL DEFAULT 0.00,
  `pro_id` INT NOT NULL,
  `epr_id` INT NOT NULL,
  PRIMARY KEY (`enp_id`),
  INDEX `fk_entrada_produto_detalhe_produto1_idx` (`pro_id` ASC) VISIBLE,
  INDEX `fk_entrada_produto_detalhe_entrada_produto1_idx` (`epr_id` ASC) VISIBLE,
  CONSTRAINT `fk_entrada_produto_detalhe_produto1`
    FOREIGN KEY (`pro_id`)
    REFERENCES `gcom`.`produto` (`pro_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_entrada_produto_detalhe_entrada_produto1`
    FOREIGN KEY (`epr_id`)
    REFERENCES `gcom`.`entrada_produto` (`epr_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gcom`.`registro_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gcom`.`registro_venda` (
  `rgv_id` INT NOT NULL AUTO_INCREMENT,
  `rgv_data` DATETIME NOT NULL,
  `rgv_vlr_total` DECIMAL(22,2) NULL DEFAULT 0.00,
  `rgv_forma_pag` ENUM('dinheiro', 'debito', 'credito') NULL,
  `rgv_status` ENUM('aberto', 'finalizado') NOT NULL DEFAULT 'aberto',
  PRIMARY KEY (`rgv_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gcom`.`saida_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gcom`.`saida_produto` (
  `spr_id` INT NOT NULL AUTO_INCREMENT,
  `spr_qtd` INT NOT NULL DEFAULT 0,
  `spr_sub_total` DECIMAL(22,2) NOT NULL DEFAULT 0.00,
  `pro_id` INT NOT NULL,
  `rgv_id` INT NOT NULL,
  PRIMARY KEY (`spr_id`),
  INDEX `fk_saida_produto_produto1_idx` (`pro_id` ASC) VISIBLE,
  INDEX `fk_saida_produto_registro_venda1_idx` (`rgv_id` ASC) VISIBLE,
  CONSTRAINT `fk_saida_produto_produto1`
    FOREIGN KEY (`pro_id`)
    REFERENCES `gcom`.`produto` (`pro_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_saida_produto_registro_venda1`
    FOREIGN KEY (`rgv_id`)
    REFERENCES `gcom`.`registro_venda` (`rgv_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
